name: neural-networks-aggarwal
channels:
  - conda-forge
dependencies:
  - python=3.7

  # Data Science
  - numpy=1.17
  - scipy=1.3.1
  - pandas=0.25.2

  # Plots
  - matplotlib=3.1.1

  # Jupyter
  - nodejs=10.13.0
  - conda-forge::jupyterlab=1.1.4
  - conda-forge::ipywidgets=7.5.1
  - conda-forge::ipython=7.8.0

  - pip:
      - tqdm==4.36.1